### ISSUE TITLE
Create hackage release to support ghc 9.2 & ghc 9.4, ghc 9.6

### ISSUE THREAD

**Issue by alaendle** [co-log/co-log-polysemy#15]
.. since stackage moved to ghc 9.2.5 I think it's time for an hackage update.

**Comment by alaendle** [comment]
Current stable & supported GHC releases are series 9.2 and 9.4 - would be good to have a release that supports these compilers 🎈

**Comment by jstolarek** [comment]
Also affected by this. Can't use co-log-polysemy in my project due to GHC version restriction (I'm using GHC 9.2).

**Comment by alaendle** [comment]
Btw. Since no code has changed - even a simple hackage revision should be sufficient - no need for a new version.

**Comment by alaendle** [comment]
Still no code changes - https://github.com/co-log/co-log-polysemy/compare/v0.0.1.3...main and corresponding PR https://github.com/co-log/co-log-polysemy/pull/17 - so I just created a hackage revision https://hackage.haskell.org/package/co-log-polysemy-0.0.1.3/revisions/ - Hope this was okay.
