### ISSUE TITLE
Support GHC 9.2

### ISSUE THREAD

**Issue by chshersh** [co-log/co-log-polysemy#4]

**Comment by alaendle** [comment]
Depends on https://github.com/co-log/co-log-core/issues/7!

**Comment by udaycruise2903** [comment]
hey @chshersh, how essential is the support required for 9.2.1.  You were adding some GHC warnings to co-log-core so i thought of asking. 
 #8 had support commit over old commits and it does not pass any checks. So i will redo that PR again from a clean branch.

**Comment by chshersh** [comment]
@udaycruise2903 `co-log-core` with GHC 9.2 is not released yet. See the following comment:

* https://github.com/co-log/co-log-core/pull/8#issuecomment-1026952478

Once it's released, GHC 9.2 support can be added to `co-log-polysemy` without problems 🙂

**Comment by vrom911** [comment]
Resolved in #14
