### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by chshersh** [co-log/co-log-polysemy#5]
Current README duplicates previous co-log README. Ideally, we want to see here something like in the following README of `prolens` with a short description and simple usage.

* https://github.com/kowainik/prolens#readme

**Comment by NguyenLyy** [comment]
I want to do it. Can you guide me?

**Comment by chshersh** [comment]
Hi @NguyenLyy 👋🏻 

Thanks for your interest! A good starting point would be to replace the `co-log-polysemy` README with a copy-paste of `prolens` README and change the package name. Most sections of that README probably can be skipped. I believe, you don't need to describe the goals of `co-log-polysemy`, its features and comparison to other libraries, this would be too much to ask 😅 But the "How to use" section has a generic template. And you can take a general introduction description of the package from the `.cabal` file.

**Comment by udaycruise2903** [comment]
#6 check here.

**Comment by udaycruise2903** [comment]
I have a confusion regarding dependencies that should be added for co-log-polysemy in .cabal files.

my #6 PR mentions - 
build-depends: base ^>= LATEST_SUPPORTED_BASE
             , co-log-polysemy ^>= LATEST_VERSION

shouldn't that be -
build-depends: base ^>= LATEST_SUPPORTED_BASE
                         co-log-core ^>= LATEST_VERSION
                       , polysemy >= LATEST_VERSION

**Comment by udaycruise2903** [comment]
I have a confusion regarding dependencies that should be added for co-log-polysemy in .cabal files.

my #6 PR mentions -
build-depends: base ^>= LATEST_SUPPORTED_BASE
                           , co-log-polysemy ^>= LATEST_VERSION

shouldn't that be -
build-depends: base ^>= LATEST_SUPPORTED_BASE
                           , co-log-core ^>= LATEST_VERSION
                           , polysemy >= LATEST_VERSION

**Comment by chshersh** [comment]
@udaycruise2903 Yes, you're correct. The example now imports `Polysemy` explicitly so it should depend on this library as well. Would you like to open a small PR with this small fix? 🙂

**Comment by udaycruise2903** [comment]
review #7. It has the fix.

**Comment by chshersh** [comment]
I believe this is finally fixed 🙂 
Thanks @udaycruise2903!
